Add command line arg parsing

diff --git a/drifter b/drifter
--- a/drifter
+++ b/drifter
@@ -2,14 +2,6 @@
 
 set -eo pipefail
 
-## 🧔🏻 Drifter, a small vagrant, powered by multipass
-## All commands require the name of the VM to be passed e.g.
-## # drifter dev ssh
-## or
-## # drifter provision dev ./my/vm.sh
-## Version=0.0.1
-## Commands:
-
 log() {
   logger -t drifter -s -- "$*"  > /dev/stderr
 }
@@ -45,7 +37,7 @@ drifter_launch_if_necessary() {
 
 }
 
-drifter_start_if_necessary() {
+drifter_command_start() {
   local name=$1
   drifter_launch_if_necessary $name
   if [[ "$(multipass info $name --format json | jq -r .info.$name.state)" != "Running" ]] ; then
@@ -56,7 +48,7 @@ drifter_start_if_necessary() {
   fi
 }
 
-drifter_stop() {
+drifter_command_stop() {
   local name=$1
   log "stopping $name"
   multipass stop $name
@@ -70,7 +62,7 @@ drifter_suspend() {
   exit 0
 }
 
-drifter_provision() {
+drifter_command_provision() {
   local name=$1
   local provisionScript=$2
   log "provisioning $name with $provisionScript"
@@ -79,10 +71,7 @@ drifter_provision() {
   exit 0
 }
 
-
-
-
-drifter_shell() {
+drifter_command_shell() {
   local name=$1
   log "starting $name shell"
   multipass shell $name
@@ -90,7 +79,7 @@ drifter_shell() {
 }
 
 # TODO: configurable tunnels!
-drifter_tunnels() {
+drifter_command_tunnels() {
   local name=$1
   local ip=$2
   log "starting $name tunnels (ip: $ip)"
@@ -106,7 +95,7 @@ drifter_tunnels() {
       -L 9630:localhost:9630
 }
 
-drifter_ssh() {
+drifter_command_ssh() {
   local name=$1
   local ip=$2
   log "sshing to $name (ip: $ip)"
@@ -122,9 +111,26 @@ drifter_ip() {
   echo $ip
 }
 
+dirfter_command_ip() {
+  echo $(drifter_ip $name)
+}
 
 drifter_help() {
+  # Parses out all lines starting with ## to generate docs
   grep '##' $0 | grep -v grep | sed 's/## //g'
+  ## 🧔🏻 Drifter, a small vagrant, powered by multipass
+  ## All commands require the name of the VM to be passed e.g.
+  ## # drifter -n dev -c ssh
+  ## # drifter -n work -c tunnels
+  ## Version=0.0.1
+  ## or
+  ## # drifter -c provision -n dev -p ./my/vm.sh
+  ## Args:
+  ## -n name of the vm (one of: dev, work)
+  ## -c command
+  ## -p if command is provision, path to the bash script to run in the machine
+
+  ## Commands:
 }
 
 # Entry point
@@ -158,28 +164,29 @@ drifter_main() {
   case $command in
     start)
       drifter_launch_if_necessary $name
-      drifter_start_if_necessary $name
+      drifter_command_start $name
       ;;
     suspend) ## Suspend the VM. Unsupported right now
-      drifter_suspend $name
+      drifter_command_suspend $name
       ;;
     stop) ## Stop the VM
-      drifter_stop $name
+      drifter_command_stop $name
       ;;
     provision) ## Provision the VM with given Bash script
-      drifter_provision $name $provisionScript
+      drifter_command_provision $name $provisionScript
       ;;
     tunnels) ## Start a SSH session with multiple ports opened
-      drifter_tunnels $name $(drifter_ip $name)
+      drifter_command_tunnels $name $(drifter_ip $name)
       ;;
     shell) ## Start a shell, no agent or tunnels opened
-      drifter_shell $name
+      drifter_command_shell $name
       ;;
     ssh) ## Start a SSH session with SSH agent forwarded
-      drifter_ssh $name $(drifter_ip $name)
+      drifter_command_ssh $name $(drifter_ip $name)
       ;;
     ip) ## Find the IP of the VM
-      echo $(drifter_ip $name)
+      drifter_command_ip $name
+
       ;;
     *)
       drifter_help
@@ -188,7 +195,32 @@ drifter_main() {
     esac
 }
 
+# Entrypoint
+name=
+command=
+provisionScript=
 
+while getopts "n:c:s:h" OPTIONS; do
+  case "$OPTIONS" in
+    h)
+      drifter_help
+      exit 0
+      ;;
+    n)
+      name="$OPTARG"
+      ;;
+    c)
+      command="$OPTARG"
+      ;;
+    p)
+      provisionScript="$OPTARG"
+      ;;
+  esac
+done
 
-# name / command / optional provision script
-drifter_main "$1" "$2" "$3"
+if [[ "$name" == ""  ]] || [[ "$command" == "" ]] ; then
+  echo "missing name (given: $name) or command (given: $command)"
+  exit 1
+fi
+
+drifter_main "$name" "$command" "$provisionScript"
